### ISSUE TITLE
Possible bug in env_vars_dict property

### ISSUE THREAD

**Issue by adamhospital** [bioexcel/biobb_common#10]
https://github.com/bioexcel/biobb_common/blob/8ef480b03e04dacbfcf49586ea85ed2193a6d025/biobb_common/generic/biobb_object.py#L68

Shouldn't that be:

        self.env_vars_dict: typing.Mapping = properties.get('env_vars_dict', {})

with `env_vars_dict` instead of `check_extensions`?

**Comment by PauAndrio** [comment]
Fix. Available in the next release.
