### ISSUE TITLE
Allow newer versions of biopython

### ISSUE THREAD

**Issue by pgbarletta** [bioexcel/biobb_common#12]
Hi,
is there a reason for such a strict version requirement of biopython?

https://github.com/bioexcel/biobb_common/blob/fd47e7b5bea51cfb8906467ff121a3997840c024/setup.py#L21

This is keeping me from using other packages (eg: MDAnalysis) along side building blocks. I'd appreciate if newer versions were allowed.

Thanks for any help.

**Comment by gbayarri** [comment]
Hi, in the next release biobb_common will be updated to biopython 1.81. We hope to launch this release as soon as possible, but there are good reasons for having biopython fixed to 1.79 and we have to perform some fixes and a lot os testing before launching this new release.

Best.

**Comment by pgbarletta** [comment]
Cool, I'll wait for the next release.

**Comment by w8jcik** [comment]
Are other versions of `biopython` really not working, or is this constraint just to be on the safe side?

I am also encountering the issue with MDAnalysis being in conflict when trying to install together with `biobb`.

https://github.com/spack/spack/blob/v0.20.1/var/spack/repos/builtin/packages/py-mdanalysis/package.py#L103

**Comment by w8jcik** [comment]
It is not possible to install `biobb-analysis` together with `mdanalysis` in single Spack environment
https://github.com/spack/spack/blob/v0.20.1/var/spack/repos/builtin/packages/py-mdanalysis/package.py#L103

```
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "py-biopython"
   2. Cannot satisfy 'py-biopython@1.80:'
   3. Cannot satisfy 'py-biopython@1.79'.
```

**Comment by PauAndrio** [comment]
Hi,

Biopython constraint has been removed in biobb 4.1 release.

Regards,
Pau Andrio
